name: Build macOS

on: [ push, pull_request ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.417
    - name: Build
      run: dotnet build HL7TestingTool.sln
